server {
    listen 80;
    server_name _;

    location /videos/ {
        alias /var/www/videos/;
        autoindex off;
        sendfile on;
        tcp_nopush on;
        types {
            video/mp4 mp4;
        }
    }
}
